services:
  postgres:
    image: postgres:15
    container_name: ${DATABASE_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    env_file:
      - ./.env

  mongodb:
    image: mongo:latest
    container_name: ${MONGODB_CONTAINER}
    restart: unless-stopped
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DBNAME}
    volumes:
      - mongo_data:/data/db
      - ~/Projects-data/mongo-init:/docker-entrypoint-initdb.d:ro
    env_file:
      - ./.env
volumes:
  mongo_data:
